version: "3"
services:
  zookeeper:
    container_name: 'kafka-zookeeper'
    image: 'bitnami/zookeeper:3.8.2'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: 'kafka-kafka'
    image: 'bitnami/kafka:3.4.1'
    restart: always
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    depends_on:
      - zookeeper

